### ISSUE TITLE
OOB from relativePos (101)

### ISSUE THREAD

**Issue by mwiewior** [biodatageeks/sequila#113]
![image](https://user-images.githubusercontent.com/5020186/141692658-b8e2bc35-f81f-42a7-874c-104c309f62ba.png)
ReadSummary(2,117,[B@18cd6771,[B@1991394,true,3S14M4D14M4D14M4D14M4D14M4D14M3D9M5S)

Watchout: line 104 not 106 - shift because of adding a dummy condition!
```bash
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 1466) (192.168.1.5 executor driver): java.lang.ArrayIndexOutOfBoundsException: Index 101 out of bounds for length 101
	at org.biodatageeks.sequila.pileup.model.AggregateRDD.fillBaseQualities(ContigAggregateRDD.scala:186)
	at org.biodatageeks.sequila.pileup.model.AggregateRDD.prepareOutputQualMap(ContigAggregateRDD.scala:201)
	at org.biodatageeks.sequila.pileup.model.AggregateRDD.addBaseRecord(ContigAggregateRDD.scala:162)
	at org.biodatageeks.sequila.pileup.model.AggregateRDD.$anonfun$toPileup$3(ContigAggregateRDD.scala:63)
	at org.biodatageeks.sequila.pileup.model.AggregateRDD.$anonfun$toPileup$2(ContigAggregateRDD.scala:55)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)

```

**Comment by mwiewior** [comment]
Fixed by #115
