### ISSUE TITLE
Error while running WGS with BQ

### ISSUE THREAD

**Issue by mwiewior** [biodatageeks/sequila#40]
```
java.lang.ArrayIndexOutOfBoundsException: 101
        at org.biodatageeks.sequila.pileup.model.ExtendedReads.fillPastQualitiesFromCache(Read.scala:249)
        at org.biodatageeks.sequila.pileup.model.ExtendedReads$$anonfun$calculateAlts$1.apply(Read.scala:185)
        at org.biodatageeks.sequila.pileup.model.ExtendedReads$$anonfun$calculateAlts$1.apply(Read.scala:157)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.biodatageeks.sequila.pileup.model.ExtendedReads.calculateAlts(Read.scala:157)
        at org.biodatageeks.sequila.pileup.model.ExtendedReads.analyzeRead(Read.scala:37)
        at org.biodatageeks.sequila.pileup.model.AlignmentsRDD$$anonfun$assembleContigAggregates$1$$anonfun$apply$3$$anonfun$apply$2.apply$mcV$sp(AlignmentsRDD.scala:62)
        at org.biodatageeks.sequila.pileup.model.AlignmentsRDD$$anonfun$assembleContigAggregates$1$$anonfun$apply$3$$anonfun$apply$2.apply(AlignmentsRDD.scala:62)
        at org.biodatageeks.sequila.pileup.model.AlignmentsRDD$$anonfun$assembleContigAggregates$1$$anonfun$apply$3$$anonfun$apply$2.apply(AlignmentsRDD.scala:62)
        at scala.Option.fold(Option.scala:158)

```

```
20GAVAAXX100126:3:67:18582:79377        83      chr1    813652  17      20M4I4M4I33M1D6M1I29M   =       813372  -372    GGAGAGAAAGATGGATAGAGACAAAGAAAGAGAGAAGGAAATGAGAGAGAAAGAAGGAAGGAAGGAGGAAGAGAAAGAGGGAAAGAGAAAGAAGGAAATAA   >>DCDCEDDCCDCC744555C@=D!00/DBCB"$'5;BDDCB,)('&%$!!!!!!!!!!!!!!!!!!!!!!D!!!!!!!!!!!!!!##$%'(,,,,,,,,,   MD:Z:15A26G7G0A5^A8G0G3A5G12G2  PG:Z:BWA        RG:Z:20GAV.3    AM:i:17 NM:i:19 SM:i:17 MQ:i:17 OQ:Z:HHHHHHHHHHHHHHHHHHIHHGCHHHGGHHIHHHHHHHHHHFHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH      UQ:i:309        ZQ:Z:FF@@@@@@@@@@@@LOPNNM@@@@cRPQ@@@@b^]OH@@@@@V[Z]\_^cccaccaaccaaccaacaacca@acccacaaacccac_a`_[\XWWXXWWXW

```

**Comment by agaszmurlo** [comment]
@mwiewior podasz mi ktora to u Ciebie linijka 249?

**Comment by mwiewior** [comment]
```scala
       val qual =  if (conf.value.isBinningEnabled) (readQualSummary.qualsArray(relativePos)/conf.value.binSize).toByte  else readQualSummary.qualsArray(relativePos)
```

**Comment by mwiewior** [comment]
Fixed in #113
